#!/bin/bash

ocorrect=0
ecorrect=0
tests=0

runtest() {
  ((tests++))
  bash -c "$1 2> $2_err.my > $2.my"
  cmp $2.out $2.my > /dev/null
  if [ $? -eq 0 ]; then
    ((ocorrect++))
    printf "correct stdout, "
  else
    printf "INCORRECT STDOUT, "
  fi

  cmp $2.err $2_err.my > /dev/null
  if [ $? -eq 0 ]; then
    ((ecorrect++))
    printf "correct stderr: "
  else
    printf "INCORRECT STDERR: "
  fi

  printf "%s\n" "$1 2> $2_err.my > $2.my"
}

echo "Delete output (*.my) files from previous tests?"
echo "Press ctl-c to abort, any other key to delete the files & run tests"
read x
rm -f *.my

echo
echo "single column, numbers"
echo "  - all valid"
runtest "./csort 11 < data2" data2_11
runtest "./csort -11 < data2" data2_-11
echo "  - contains non-numbers"
runtest "./csort 1 < data1" data1_1
runtest "./csort -1 < data1" data1_-1

echo
echo "single column, strings (all valid)"
runtest "./csort 1t < data1" data1_1t
runtest "./csort -1t < data1" data1_-1t
runtest "./csort 11t < data2" data2_11t
runtest "./csort -11t < data2" data2_-11t
echo "  - needs trimming"
runtest "./csort -1t < data3" data3_-1t

echo 
echo "multiple columns, sorted only as numbers"
echo "  - all valid"
runtest "./csort 1,-2,3 < data4" data4_1,-2,3
runtest "./csort 1,2,3 < data4" data4_1,2,3
runtest "./csort 3,2,1 < data4" data4_3,2,1
echo "  - contains non-numbers"
runtest "./csort 1,-2,3 < data5" data5_1,-2,3 
runtest "./csort 1,2,3 < data5" data5_1,2,3 
runtest "./csort 3,2,1 < data5" data5_3,2,1

echo
echo "multiple columns, sorted only as strings"
echo "  - all valid"
runtest "./csort 1t,-2t,3t < data4" data4_1t,-2t,3t
runtest "./csort 1t,2t,3t < data4" data4_1t,2t,3t
runtest "./csort 3t,2t,1t < data4" data4_3t,2t,1t
runtest "./csort 1t,-2t,3t < data6" data6_1t,-2t,3t
runtest "./csort 1t,2t,3t < data6" data6_1t,2t,3t
echo "  - contains empty strings"
runtest "./csort 1t,2t,3t < data8" data8_1t,2t,3t


echo
echo "multiple columns, sorted as both numbers & strings (all valid)"
runtest "./csort 3,-1t,5 < data7" data7_3,-1t,5
runtest "./csort 3,-1t,5t < data7" data7_3,-1t,5t
runtest "./csort 1t,-3,-5 < data7" data7_1t,-3,-5
runtest "./csort 1t,-3,-5t < data7" data7_1t,-3,-5t

#echo
#echo "Passed: $ocorrect (stdout), $ecorrect (stderr) (out of $tests tests)" 

